pipeline{
    agent any
    environment {
        app_version = 'v1'
        rollback = 'true'
    }
    stages{
        stage("Testing"){
            steps{

            }
        }
        stage("Build & Push"){
            steps{

            }
        }
        stage("Config Management"){
            steps{

            }
        }
        stage("Deploy"){
            steps{
                
            }
        }
    }

}